### ISSUE TITLE
Adapt `synergise` to new 3D grid search

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#81]
The new 3D grid search introduced in https://github.com/lgatto/synapter/pull/68 (already merged into the 2.0 branch) causes some problems:

- [x] `synergise` fails. `getGrid` returns an array instead of a matrix. How to put this in the HTML report?
- [ ] ~~`synergise` needs the following arguments `imdiff.from`, `imdiff.to` and `imdiff.by`~~ => `synergize2` #119 
- [ ] ~~`plotFeatures` can plot *m/z* vs ion mobility as well (should be detected automatically by `synergise`)~~ => `synergize2` #119 
- [ ] ~~`plotGrid` has a new `maindim` feature (could be `c("im", "rt", "mz")`; maybe `synergise` should use all three if ion mobility is available).~~ => `synergize2` #119
